apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: tanzu-java-web-app
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: deliverable
    app.tanzu.vmware.com/deliverable-type: web
spec:
  source:
    image: harbor.gcp.ianad.dev/tanzu/supply-chain/tanzu-java-web-app-dev-bundle:20fb6233-9134-4372-b9f7-238fb9830b09
